import "./viewBucket.styles.css";
function ViewBucket() {
  const listItem = [
    "Coffee mug",
    "Bicycle",
    "Pineapple",
    "Sunglasses",
    "Backpack",
    "Guitar",
    "Rubber duck",
    "Umbrella",
    "Laptop",
    "Chess board",
    "Post-it notes",
    "Hiking boots",
    "Candles",
    "Wristwatch",
    "Sunflower",
    "Headphones",
    "Baseball cap",
    "Telescope",
    "Puzzle",
    "Cookie jar",
    "Hammock",
    "Flip-flops",
    "Soccer ball",
    "Plant pot",
    "Roller skates",
    "Passport",
    "Fishing rod",
    "Compass",
    "Sunglasses case",
    "Water bottle",
    "Yoga mat",
    "Car keys",
    "Rubber band",
    "Earrings",
    "Picture frame",
    "Alarm clock",
    "Frisbee",
    "Fountain pen",
    "Remote control",
    "Avocado",
    "Socks",
    "Beach towel",
    "Backpack",
    "Coloring book",
    "Toothbrush",
    "Playing cards",
    "Hot air balloon",
    "Skateboard",
    "Can opener",
    "Dinosaur figurine",
    "Wind chimes",
    "Calculator",
    "T-shirt",
    "Pencil sharpener",
    "Keychain",
    "Paperclip",
    "Bubblegum",
    "Hula hoop",
    "Snow globe",
    "Rubik's cube",
    "Hairbrush",
    "Hand sanitizer",
    "Wallet",
    "Stuffed animal",
    "Power bank",
    "Postcard",
    "Garden gnome",
    "Perfume bottle",
    "Candy cane",
    "Tote bag",
    "Guitar pick",
    "Scented candle",
    "Luggage tag",
    "Tennis racket",
    "Coins",
    "Nail clippers",
    "Champagne flute",
    "Bookmarks",
    "Pinecone",
    "USB drive",
    "Tarot cards",
    "Chopsticks",
    "Notebook",
    "Cookie cutter",
    "Miniature sailboat",
    "Bowling ball",
    "Glow stick",
    "Chess piece (pawn)",
    "Stopwatch",
    "Kaleidoscope",
    "Pocket mirror",
    "Bottle opener",
    "Cocktail umbrella",
    "Paintbrush",
    "Marble",
    "Mouse pad",
    "Bookmark",
    "Pill bottle",
    "Seashell",
    "Playing dice",
  ];

  return (
    <div className="bucket-list-container">
      <div className="bucket-list-title">Here you can view the whole list</div>
      <div className="list-items-container">
        {listItem.map((item, index) => (
          <div className="list-item" key={index}>
            {item}
          </div>
        ))}
      </div>
    </div>
  );
}

export default ViewBucket;
